export const headphones_type = [
    'Внутриканальные',
    'Вкладыши',
    'Накладные',
    'Полноразмерные',
]   // тип наушников
export const headphones_brand = [
    "1More",
    "2E",
    "A4Tech",
    "ACME",
    "AKG",
    "Anker",
    "Apple",
    "ASUS",
    "Atomic",
    "Audeze",
    "Audio-Technica",
    "Awei",
    "Axtel",
    "Bang &amp; Olufsen",
    "Baseus",
    "BBK",
    "Beats",
    "Beyerdynamic",
    "Blast",
    "Borofone",
    "Bose",
    "BQ",
    "Brainwavz",
    "Canyon",
    "Celebrat",
    "Corsair",
    "Cougar",
    "Creative",
    "CrownMicro",
    "D&amp;A",
    "Defender",
    "Dialog",
    "Digma",
    "Dunu",
    "Edifier",
    "Elari",
    "Eltronic",
    "Evolution",
    "EXPERTS",
    "Freestyle",
    "GAL",
    "Gembird",
    "Genesis",
    "Genius",
    "Harper",
    "Haylou",
    "Hiper",
    "Hoco",
    "HONOR",
    "HP",
    "Huawei",
    "HyperX",
    "InterStep",
    "Jabra",
    "JBL",
    "Jet.A",
    "JVC",
    "KOSS",
    "KZ Acoustics",
    "LG",
    "Logitech",
    "Marshall",
    "Marvo",
    "Master &amp; Dynamic",
    "MEIZU",
    "Microlab",
    "Microsoft",
    "Motorola",
    "Nobby",
    "Nokia",
    "Oklick",
    "Olmio",
    "Omega",
    "Oppo",
    "Padmate",
    "Panasonic",
    "Perfeo",
    "Philips",
    "Pioneer",
    "Platinet",
    "QCY",
    "QUMO",
    "Razer",
    "Realme",
    "Red Line",
    "Redragon",
    "Ritmix",
    "Rombica",
    "Sabbat",
    "Samsung",
    "SBOX",
    "Sennheiser",
    "Shure",
    "Skullcandy",
    "Smart Buy",
    "Sony",
    "Soul",
    "SoundMagic",
    "SteelSeries",
    "SVEN",
    "TCL",
    "TFN",
    "TFZ",
    "TRN",
    "Urbanears",
    "Vsonic",
    "White Shark",
    "WiWU",
    "Xiaomi",
    "Yison",
    "Другой",
]   // производитель
export const headphones_connector = [
    '3.5 мм',
    '2x3.5 мм',
    'USB Type-A',
    'USB Type-C',
    'Lightning',
    '6.3 мм',
    'microUSB',
]   // тип разъёма
export const headphones_purpose = [
    'Игровые',
    'Спортивные',
    'Мониторные',
    'Для DJ',
    'Детские',
    'Без специализации',
]    // назначение
export const headphones_fastening = [
    'Внутри уха',
    'Оголовье',
    'Затылочная дужка',
    'Заушное крепление',
    'На шее',
]   // крепление