export const truck_brand = [
    "ASTRA",
    "Asia",
    "Autosan",
    "Avia",
    "BAW",
    "Beifang Benchi",
    "Bova",
    "CAMC",
    "Changan",
    "Citroen",
    "DAF",
    "Daewoo",
    "Daihatsu",
    "DongFeng",
    "EOS",
    "Evobus",
    "FAW",
    "Fiat",
    "Ford",
    "Foton",
    "Foxbus",
    "Freightliner",
    "GMC",
    "Golden Dragon",
    "Hania",
    "Higer",
    "Hino",
    "Howo",
    "Hyundai",
    "IFA",
    "Ikarus",
    "International",
    "Irisbus",
    "Isuzu",
    "Iveco",
    "JAC",
    "JMC",
    "Kenworth",
    "Kia",
    "King Long",
    "MAN",
    "Mack",
    "Magirus",
    "Marcopolo",
    "Mazda",
    "Mercedes",
    "Mitsubishi",
    "Mudan",
    "Naveco",
    "Neoplan",
    "Nissan",
    "Nysa",
    "Opel",
    "Otokar",
    "Otoyol",
    "Peterbilt",
    "Peugeot",
    "Renault",
    "Robur",
    "SOR Libchavy",
    "Sanos",
    "Scania",
    "Setra",
    "Shacman (Shaanxi)",
    "ShenLong (Sunlong)",
    "Shuchi",
    "Silant",
    "Simaz",
    "Sisu",
    "Sitrak",
    "Solaris",
    "SsangYong",
    "Sterling",
    "Steyr",
    "TAM",
    "TATA",
    "Tatra",
    "Temsa",
    "Tiema",
    "Toyota",
    "Van Hool",
    "Volgabus",
    "Volkswagen",
    "Volvo",
    "WAW",
    "Yuejin",
    "Yutong",
    "Zhong Tong",
    "Zuk",
    "Автотор",
    "БАЗ",
    "БЕЛА",
    "БЗКТ",
    "БелАЗ",
    "Богдан",
    "ВИС",
    "Вездеходы ГВА",
    "Воложанин",
    "ГАЗ",
    "ГАЗ-САЗ",
    "ЗиЛ",
    "Иж",
    "КАЗ",
    "КЗКТ",
    "КаВЗ",
    "КамАЗ",
    "КрАЗ",
    "ЛАЗ",
    "ЛИАЗ",
    "Люблин",
    "МАЗ",
    "МАЗ-МАН",
    "МАРЗ",
    "МЗКТ",
    "Неман",
    "НефаЗ",
    "ПАЗ",
    "СААЗ",
    "САРЗ",
    "Тонар",
    "УАЗ",
    "Урал",
    "УралАЗ",
    "ЯРОВИТ МОТОРС",
    "Яровит",
    "Другая",
]   // марки грузовиков/автобусов
export const truck_type = [
    'Полуприцеп',
    'Рефрижератор',
    'Контейнеровоз',
    'Открытая бортовая',
    'Открытая платформа',
    'Автоцистерна',
    'Автовоз',
    'Зерновоз',
    'Самосвал',
    'Лесовоз',
    'Автосцепка',
    'Фургон',
    'Изотерм',
    'Седельный тягач',
    'Автобус',
]    // тип грузовика
export const truck_capacity = [
    '< 3 т',
    '3 т',
    '4 т',
    '5 т',
    '6 т',
    '7 т',
    '8 т',
    '9 т',
    '10 т',
    '11 т',
    '12 т',
    '13 т',
    '14 т',
    '15 т',
    '16 т',
    '17 т',
    '18 т',
    '19 т',
    '20 т',
    '> 20 т',
]    // грузоподъёмность
export const truck_transmission = [
    'Автоматическая',
    'Механическая',
]   // тип коробки передач